### PR TITLE
Multi exp page responsive design

### PR DESCRIPTION
**Pull request by UAMS16**
image
image
image
image
image

### CODE REVIEW

**Comment by tncowart** [comment]
If the experiment name is at all long, the top box gets wider than the screen:

Screenshot 2024-09-05 at 10-33-04 Experiments

**Review by tncowart — CHANGES_REQUESTED** [review]
Just a couple of things!

**Comment by UAMS16** [comment]
Should be good to go!

**Comment by tncowart** [comment]
The padding at the bottom of the modal is missing. There should be like 5 pixels, I think?
Screenshot 2024-09-05 at 11-26-33 Experiments

**Review by tncowart — CHANGES_REQUESTED** [review]
Fix modal padding.

**Comment by UAMS16** [comment]
The padding is being responsive to the shrinking of the modal. The padding is still there.

**Comment by tncowart** [comment]
The padding at the _bottom_ of the modal shouldn't be affected by changing the _width_ of the modal. Here's the same modal in the main branch. Notice the padding:

Screenshot 2024-09-05 at 11-36-00 Experiments

**Comment by UAMS16** [comment]
This is what I am getting. Padding is still here. Padding for me shrinks when modal gets smaller
image

**Comment by tncowart** [comment]
I'm not sure what you're trying to convince me of. Are you saying that the table running of the bottom of the modal is fine?

**Comment by UAMS16** [comment]
Didn't comment on aesthetics. Looking at the code, the padding wasn't changed and image in the last message shows padding. Got to figure out why the padding is shrinking for me.

**Comment by tncowart** [comment]
I just noticed that the experiment boxes in the modal aren't as wide as they could be. Shouldn't they be as wide as the drop-down menus?

Screenshot 2024-09-05 at 11 54 11 AM

**Comment by UAMS16** [comment]
image
Mobile view

**Comment by UAMS16** [comment]
Tablet view 
image

Will see whats going on

**Review by tncowart — APPROVED** [review]
Looks good!

**Pull request merged**
